CREATE TABLE spaces(id SERIAL PRIMARY KEY, name VARCHAR(40));

CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(40));

ALTER TABLE users ADD COLUMN password VARCHAR(60);
ALTER TABLE users ADD COLUMN username VARCHAR(60);
ALTER TABLE users ADD COLUMN email VARCHAR(60);
